name: Test
on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 17.3.0
            - name: Install dependencies
              run: yarn run ci
            - name: Run tests
              run: yarn test:ci
