name: ReleaseTypes
on:
    workflow_dispatch:

    workflow_run:
        workflows: [Release]
        types:
            - completed

jobs:
    release:
        name: Release Types
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Build and merge.
              uses: ./.github/actions/typed
              with:
                  gh_token: ${{ secrets.GITHUB_TOKEN }}
#           - name: Setup Node.js
#             uses: actions/setup-node@v2
#             with:
#                 node-version: 'lts/*'

#           - name: Install dependencies
#             run: npm run ci

#           - name: Build and merge.
#             run: npm run build:types
#             env:
#                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
