name: ReleaseTypes
on:
    workflow_dispatch:

    workflow_run:
        workflows: [Release]
        types:
            - completed

jobs:
    release:
        name: Release Types
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Build and merge.
              uses: ./.github/actions/typed
              with:
                  gh_token: ${{ secrets.GITHUB_TOKEN }}
